#pragma once
#include "String.h"

enum class JsonCommandType {
    OPEN_COMMAND,
    CLOSE_COMMAND,
    VALIDATE_COMMAND,
    PRINT_COMMAND,
    SEARCH_COMMAND,
    TRAVERSE_COMMAND,
    PREVIOUS_COMMAND,
    GO_BACK_COMMAND,
    UNDO_COMMAND,
    UNDO_ALL_COMMAND,
    RENAME_COMMAND,
    SET_COMMAND,
    SET_EMPTY_OBJECT_COMMAND,
    SET_EMPTY_ARRAY_COMMAND,
    SET_STRING_COMMAND,
    SET_KEYWORD_COMMAND,
    SET_NUMBER_COMMAND,
    CREATE_IN_ARRAY_COMMAND,
    CREATE_IN_OBJECT_COMMAND,
    CREATE_EMPTY_OBJECT_IN_ARRAY_COMMAND,
    CREATE_EMPTY_OBJECT_IN_OBJECT_COMMAND,
    CREATE_EMPTY_ARRAY_IN_ARRAY_COMMAND,
    CREATE_EMPTY_ARRAY_IN_OBJECT_COMMAND,
    CREATE_STRING_IN_ARRAY_COMMAND,
    CREATE_STRING_IN_OBJECT_COMMAND,
    CREATE_KEYWORD_IN_ARRAY_COMMAND,
    CREATE_KEYWORD_IN_OBJECT_COMMAND,
    CREATE_NUMBER_IN_ARRAY_COMMAND,
    CREATE_NUMBER_IN_OBJECT_COMMAND,
    REMOVE_COMMAND,
    MOVE_FROM_COMMAND,
    MOVE_TO_ARRAY_COMMAND,
    MOVE_TO_OBJECT_COMMAND,
    SAVE_COMMAND,
    SAVE_AS_COMMAND,
    HELP_COMMAND,
    EXIT_COMMAND
};

class JsonCommand {
private:
    JsonCommandType _type;

public:
    explicit JsonCommand(JsonCommandType type);
    virtual ~JsonCommand() = default;

    JsonCommandType getType() const;

    virtual void execute() const = 0;

    static void saveChangesPrompt();
};
